#!/usr/bin/env python3
"""Bounded lab observations; unknown diagnostics/results never produce acceptance.
First observations need a reviewed frozen golden contract, not self-approval.
"""
import argparse,ast,base64,hashlib,json,subprocess,sys
from pathlib import Path,PurePosixPath
HERE=Path(__file__).resolve().parent;ROOT=HERE.parents[3]
SSH=['ssh','-T','-F','/tmp/kaltura-php74-ssh.conf','baseline74'];STAGE='/home/vagrant/php-generator-debug-v1'
MANIFEST=ROOT/'doc/php83/evidence/template-generation/generator-debug-v1/manifest.json'
CASES=ROOT/'doc/php83/evidence/template-generation/case-plan.json'
REFERENCE=ROOT/'doc/php83/evidence/exp10-runtime/runtime-before.json'
SNAPSHOT=ROOT/'tools/php83/exp10-api/runtime-identity.py'
SNAPSHOT_PIN='f2985a7d3f054c3a743535009e0ad2937545d05e1c0d9e7c936a24acf13da463'
REFERENCE_PIN='df1a5a5901a6f9862e8930f2d80dafd6e294da78ab07618cd9683331f758db5c'
VARIANTS=[('74','prerequisite'),('83','prerequisite'),('74','debug'),('83','debug')]
HARNESS=['build.py','probe.php','run.sh','collect.py','test_build.py','test_collect.py','validate.py','test_validate.py']
def sha(b):return hashlib.sha256(b).hexdigest()
def require(ok,msg):
 if not ok:raise ValueError(msg)
def remote(args,data=None):
 try:r=subprocess.run(SSH+args,input=data,capture_output=True,timeout=75);return {'exit':r.returncode,'stdout':r.stdout.decode(),'stderr':r.stderr.decode()}
 except subprocess.TimeoutExpired:return {'exit':124,'stdout':'','stderr':'collector timeout'}
def parse_checksums(stdout):
 import re
 require(type(stdout) is str and stdout and stdout.endswith('\n'),'Malformed checksum stream')
 result={}
 for line in stdout.splitlines():
  match=re.fullmatch(r'([0-9a-f]{64})  (/[^\s]+)',line)
  require(match is not None,'Malformed checksum row')
  pin,path=match.groups();require(path not in result,'Duplicate checksum path');result[path]=pin
 return result

def identities(manifest):
 expected={STAGE+'/'+n:sha((HERE/n).read_bytes()) for n in ['probe.php','run.sh']}
 for path,pins in manifest['files'].items():
  for variant in ['original','exp10','prerequisite','debug']:expected[STAGE+'/'+variant+'/'+path]=pins[variant]
 r=remote(['sha256sum '+' '.join(expected)]);require(r['exit']==0,'Remote identity command failed')
 require(parse_checksums(r['stdout'])==expected,'Stage hash mismatch')
 # Reuse audited literal snapshot program; do not execute its CLI/main or eval arbitrary AST.
 require(sha(SNAPSHOT.read_bytes())==SNAPSHOT_PIN,'Audited snapshot helper drift')
 require(sha(REFERENCE.read_bytes())==REFERENCE_PIN,'Runtime reference drift')
 tree=ast.parse(SNAPSHOT.read_text());literals=[ast.literal_eval(n.value) for n in tree.body if isinstance(n,ast.Assign) and any(isinstance(t,ast.Name) and t.id=='REMOTE' for t in n.targets)]
 require(len(literals)==1 and type(literals[0]) is str,'Snapshot literal mismatch')
 r=remote(['python3 -'],literals[0].encode());require(r['exit']==0,'Runtime snapshot failed')
 require(json.loads(r['stdout'])==json.loads(REFERENCE.read_text())['identity'],'Runtime differs from pinned lab reference')
 return {'stage':expected,'runtime':json.loads(r['stdout']),'snapshot_helper_sha256':sha(SNAPSHOT.read_bytes()),'snapshot_program_sha256':sha(literals[0].encode())}
def decode_outputs(body):
 result={}
 outputs=body['outputs']
 if type(outputs) is list and len(outputs)==0:return result
 require(type(outputs) is dict,'Generated outputs must be object or empty PHP array')
 for path,item in outputs.items():
  require(type(path) is str and path and not PurePosixPath(path).is_absolute() and '..' not in PurePosixPath(path).parts,'Unsafe generated path')
  data=base64.b64decode(item['base64'],validate=True);require(sha(data)==item['sha256'],'Generated byte hash mismatch');result[path]=data
 return result

def parse_record(record,manifest):
 require(type(record['exit']) is int and record['exit'] in [0,10],'Unknown process status (native fatal is not an accepted control)')
 b=json.loads(record['stdout']);require((b['mode'],b['case'])==(record['mode'],record['case']),'Case mismatch')
 require(b['runtime'].startswith('7.4.' if record['runtime']=='74' else '8.3.'),'Runtime mismatch')
 require((b['exception'] is None)==(record['exit']==0),'Exception/exit mismatch')
 require(type(b['loaded']) is dict and b['loaded'],'Missing loaded source identity')
 for path,pin in b['loaded'].items():require(path in manifest['files'] and pin==manifest['files'][path][record['variant']],'Loaded source drift')
 decode_outputs(b);return b

def validate_matrix(records,cases):
 expected=[(r,v,mode,case) for r,v in VARIANTS for mode,items in cases.items() for case in items]
 require([(r['runtime'],r['variant'],r['mode'],r['case']) for r in records]==expected,'Missing/duplicate/reordered matrix rows')
 require(all(type(r['exit']) is int and r['exit'] in [0,10] for r in records),'Unknown matrix status')
 return len(expected)
def persist(path,report):
 # Unique sibling file prevents a stale prior attempt from blocking terminal evidence.
 import os,tempfile
 descriptor,name=tempfile.mkstemp(prefix=path.name+'.progress-',suffix='.tmp',dir=path.parent)
 tmp=Path(name)
 try:
  with os.fdopen(descriptor,'w') as f:
   json.dump(report,f,indent=2);f.write('\n');f.flush();os.fsync(f.fileno())
  tmp.replace(path)
 finally:
  tmp.unlink(missing_ok=True)
def main():
 import signal
 p=argparse.ArgumentParser();p.add_argument('output',type=Path);p.add_argument('--phase',choices=['generate'],default='generate');a=p.parse_args()
 with a.output.open('x') as f:f.write('{}\n')
 report={'schema':2,'status':'INITIALIZING','phase':a.phase,'runtime_acceptance':False,'generated_syntax_acceptance':False,'application_acceptance':False,'records':[],'failures':[],'identity_before':None,'identity_after':None,'harness_sha256':{n:sha((HERE/n).read_bytes()) for n in HARNESS},'limitations':['Observation only; reviewed exact diagnostic/native stderr and output goldens remain required. No generated application execution or semantic acceptance.']}
 def interrupted(signum,frame):raise InterruptedError('signal '+str(signum))
 signal.signal(signal.SIGTERM,interrupted);signal.signal(signal.SIGINT,interrupted)
 persist(a.output,report)
 try:
  require(sha(MANIFEST.read_bytes())=='2c9d61197bbe27c448792d256c93a6645018e022d38eec089c938c9660000f0b','Pinned DEBUG manifest drift');manifest=json.loads(MANIFEST.read_text());require(sha(CASES.read_bytes())=='eae8ad799e7d66f2cbf0e583170ded28c35c9b1699ad46cd91e146771f536e67','Pinned case matrix drift');allcases=json.loads(CASES.read_text())['modes'];cases={'generate':allcases['generate']}
  report['input_pins']={str(MANIFEST):sha(MANIFEST.read_bytes()),str(CASES):sha(CASES.read_bytes())}
  report['identity_before']=identities(manifest);report['status']='RUNNING';persist(a.output,report)
  for runtime,variant in VARIANTS:
   for mode,items in cases.items():
    for case in items:
     cmd=f'bash {STAGE}/run.sh {runtime} {variant} {mode} {case}'
     report['pending']=[runtime,variant,mode,case];persist(a.output,report)
     record={'runtime':runtime,'variant':variant,'mode':mode,'case':case,'command':cmd,**remote([cmd])};record['stderr_sha256']=sha(record['stderr'].encode());record['lints']=[]
     report['records'].append(record);persist(a.output,report)
     try:
      body=parse_record(record,manifest)
      for path,data in decode_outputs(body).items():
       if path.endswith('.php') and mode!='method':
        for lint_runtime in ['74','83']:
         lint=remote([f'bash {STAGE}/run.sh {lint_runtime} {variant} lint stdin'],data)
         record['lints'].append({'path':path,'runtime':lint_runtime,**lint});persist(a.output,report)
         require(type(lint['exit']) is int and lint['exit'] in [0,255],'Unknown lint status')
     except (ValueError,KeyError,TypeError) as e:report['failures'].append({'row':[runtime,variant,mode,case],'error':str(e)})
     report.pop('pending',None);persist(a.output,report)
  report['identity_after']=identities(manifest);require(report['identity_before']==report['identity_after'],'Runtime/input drift');validate_matrix(report['records'],cases)
  report['status']='OBSERVED_PENDING_REVIEWED_CONTRACT' if not report['failures'] else 'FAILED_OBSERVATION_VALIDATION'
 except (Exception,KeyboardInterrupt) as e:
  report['status']='INTERRUPTED_OR_FAILED';report['terminal_error']={'type':type(e).__name__,'message':str(e)}
 finally:persist(a.output,report)
 print(json.dumps({'status':report['status'],'rows':len(report['records']),'failures':len(report['failures'])}));return 2
if __name__=='__main__':sys.exit(main())
