#!/usr/bin/env python3
"""Bounded lab observations; unknown diagnostics/results never produce acceptance.
First observations need a reviewed frozen golden contract, not self-approval.
"""
import argparse,ast,base64,hashlib,json,subprocess,sys
from pathlib import Path,PurePosixPath
HERE=Path(__file__).resolve().parent;ROOT=HERE.parents[2]
SSH=['ssh','-T','-F','/tmp/kaltura-php74-ssh.conf','baseline74'];STAGE='/home/vagrant/php-template-generation-r1'
MANIFEST=ROOT/'patches/php83/held/pake-relative-path/manifest.json'
CASES=ROOT/'doc/php83/evidence/template-generation/case-plan.json'
SNAPSHOT=ROOT/'tools/php83/exp10-api/runtime-identity.py'
VARIANTS=[('74','original'),('74','exp10'),('83','exp10'),('74','candidate'),('83','candidate')]
HARNESS=['build.py','probe.php','run.sh','collect.py','test_build.py']
def sha(b):return hashlib.sha256(b).hexdigest()
def require(ok,msg):
 if not ok:raise ValueError(msg)
def remote(args,data=None):
 try:r=subprocess.run(SSH+args,input=data,capture_output=True,timeout=75);return {'exit':r.returncode,'stdout':r.stdout.decode(),'stderr':r.stderr.decode()}
 except subprocess.TimeoutExpired:return {'exit':124,'stdout':'','stderr':'collector timeout'}
def identities(manifest):
 expected={STAGE+'/'+n:sha((HERE/n).read_bytes()) for n in ['probe.php','run.sh']}
 for path,pins in manifest['files'].items():
  for variant in ['original','exp10','candidate']:expected[STAGE+'/'+variant+'/'+path]=pins[variant]
 r=remote(['sha256sum '+' '.join(expected)]);require(r['exit']==0,'Remote identity command failed')
 require({line.split()[1]:line.split()[0] for line in r['stdout'].splitlines()}==expected,'Stage hash mismatch')
 # Reuse audited literal snapshot program; do not execute its CLI/main or eval arbitrary AST.
 tree=ast.parse(SNAPSHOT.read_text());literals=[ast.literal_eval(n.value) for n in tree.body if isinstance(n,ast.Assign) and any(isinstance(t,ast.Name) and t.id=='REMOTE' for t in n.targets)]
 require(len(literals)==1 and type(literals[0]) is str,'Snapshot literal mismatch')
 r=remote(['python3 -'],literals[0].encode());require(r['exit']==0,'Runtime snapshot failed')
 return {'stage':expected,'runtime':json.loads(r['stdout']),'snapshot_helper_sha256':sha(SNAPSHOT.read_bytes()),'snapshot_program_sha256':sha(literals[0].encode())}
def decode_outputs(body):
 result={}
 for path,item in body['outputs'].items():
  require(type(path) is str and path and not PurePosixPath(path).is_absolute() and '..' not in PurePosixPath(path).parts,'Unsafe generated path')
  data=base64.b64decode(item['base64'],validate=True);require(sha(data)==item['sha256'],'Generated byte hash mismatch');result[path]=data
 return result

def parse_record(record,manifest):
 require(type(record['exit']) is int and record['exit'] in [0,10,255],'Unknown process status')
 if record['exit']==255:
  require(record['variant']=='original' and record['runtime']=='83','Unexpected native fatal')
  return None
 b=json.loads(record['stdout']);require((b['mode'],b['case'])==(record['mode'],record['case']),'Case mismatch')
 require(b['runtime'].startswith('7.4.' if record['runtime']=='74' else '8.3.'),'Runtime mismatch')
 require((b['exception'] is None)==(record['exit']==0),'Exception/exit mismatch')
 require(type(b['loaded']) is dict and b['loaded'],'Missing loaded source identity')
 for path,pin in b['loaded'].items():require(path in manifest['files'] and pin==manifest['files'][path][record['variant']],'Loaded source drift')
 decode_outputs(b);return b

def validate_matrix(records,cases):
 expected=[(r,v,mode,case) for r,v in VARIANTS for mode,items in cases.items() for case in items]
 require([(r['runtime'],r['variant'],r['mode'],r['case']) for r in records]==expected,'Missing/duplicate/reordered matrix rows')
 require(all(type(r['exit']) is int and r['exit'] in [0,10,255] for r in records),'Unknown matrix status')
 return len(expected)
def main():
 p=argparse.ArgumentParser();p.add_argument('output',type=Path);a=p.parse_args();require(not a.output.exists(),'Refuse overwrite')
 manifest=json.loads(MANIFEST.read_text());cases=json.loads(CASES.read_text())['modes'];records=[];failures=[]
 before=identities(manifest)
 for runtime,variant in VARIANTS:
  for mode,items in cases.items():
   for case in items:
    cmd=f'bash {STAGE}/run.sh {runtime} {variant} {mode} {case}';record={'runtime':runtime,'variant':variant,'mode':mode,'case':case,'command':cmd,**remote([cmd])};record['stderr_sha256']=sha(record['stderr'].encode());record['lints']=[]
    try:
     b=parse_record(record,manifest)
     if b:
      for path,data in decode_outputs(b).items():
       if path.endswith('.php'):
        for lint_runtime in ['74','83']:
         lint=remote([f'bash {STAGE}/run.sh {lint_runtime} {variant} lint stdin'],data);require(type(lint['exit']) is int and lint['exit'] in [0,255],'Unknown lint status');record['lints'].append({'path':path,'runtime':lint_runtime,**lint})
    except (ValueError,KeyError,TypeError) as e:failures.append({'row':[runtime,variant,mode,case],'error':str(e)})
    records.append(record)
 after=identities(manifest);require(before==after,'Runtime/input drift');validate_matrix(records,cases)
 # No self-derived golden: first baseline observations always remain non-acceptance.
 report={'schema':1,'status':'OBSERVED_PENDING_REVIEWED_CONTRACT' if not failures else 'FAILED_OBSERVATION_VALIDATION','runtime_acceptance':False,'generated_syntax_acceptance':False,'application_acceptance':False,'input_pins':{str(MANIFEST):sha(MANIFEST.read_bytes()),str(CASES):sha(CASES.read_bytes())},'harness_sha256':{n:sha((HERE/n).read_bytes()) for n in HARNESS},'identity_before':before,'identity_after':after,'records':records,'failures':failures,'limitations':['Exact reviewed diagnostics/native-stderr and generated-output goldens remain required; no row with DEBUGfalse lint failure is waived.']}
 a.output.write_text(json.dumps(report,indent=2)+'\n');print(json.dumps({'status':report['status'],'rows':len(records),'failures':len(failures)}));return 2
if __name__=='__main__':sys.exit(main())
