#!/usr/bin/env python3
"""Source-derived expected generated bytes; no execution of generated application."""
import argparse,ast,base64,importlib.util,json
from pathlib import Path
HERE=Path(__file__).resolve().parent
s=importlib.util.spec_from_file_location('collector',HERE/'collect.py');c=importlib.util.module_from_spec(s);s.loader.exec_module(c)
CONTRACT=c.ROOT/'doc/php83/evidence/template-generation/generation-contract.json'
CONTRACT_PIN='2f352ebdaa25d8269b3daf05d134dd4943f2f48c8cce522e5398a9948c8096f3'
PREFIX='vendor/symfony-data/'
PAKE='vendor/symfony/vendor/pake/'
CASES=['module','admin','crud']+[k+'-'+v for k in ['default','rotate','controller'] for v in ['default','true','false','zero','wordfalse']]
def same(a,b):return json.dumps(a,sort_keys=True,separators=(',',':'))==json.dumps(b,sort_keys=True,separators=(',',':'))
def expected_outputs(case,control,contract,manifest):
 tokens={'PROJECT_NAME':'AuditProject','APP_NAME':'auditapp','AUTHOR_NAME':'Audit Author','MODEL_CLASS':'AuditModel','THEME':'default'}
 pairs=[]
 if case in ['module','admin','crud']:
  if control:return {}
  name={'module':'AuditModule','admin':'AuditAdmin','crud':'AuditCrud'}[case];tokens['MODULE_NAME']=name
  prefix='skeleton/module/module/' if case=='module' else 'generator/'+('sfPropelAdmin' if case=='admin' else 'sfPropelCrud')+'/default/skeleton/'
  pairs=[('apps/auditapp/modules/'+name+'/'+p,PREFIX+prefix+p) for p in (['actions/actions.class.php','templates/indexSuccess.php'] if case=='module' else ['actions/actions.class.php','config/generator.yml'])]
  if case!='admin':pairs.append(('test/functional/auditapp/'+name+'ActionsTest.php',PREFIX+'skeleton/module/test/actionsTest.php'))
 else:
  kind,setting=case.split('-',1);tokens['ENV_NAME']='dev';tokens['DEBUG']='' if setting in ['false','zero'] else '1'
  if kind=='default':tokens['BATCH_NAME']='audit_job';pairs=[('batch/audit_job.php',PREFIX+'skeleton/batch/default.php')]
  elif kind=='rotate':tokens['BATCH_NAME']='rotate_log_auditapp_prod';pairs=[('batch/rotate_log_auditapp_prod.php',PREFIX+'skeleton/batch/rotate_log.php')]
  else:tokens['CONTROLLER_NAME']='audit_front';pairs=[('web/audit_front.php',PREFIX+'skeleton/controller/controller.php')]
 result={}
 for path,template in pairs:
  entry=contract['templates'][template];data=base64.b64decode(entry['base64'],validate=True);c.require(c.sha(data)==entry['sha256']==manifest['files'][template]['original'],'Template identity mismatch')
  if not control:
   for name,value in tokens.items():data=data.replace(('##'+name+'##').encode(),value.encode())
  result[path]={'sha256':c.sha(data),'base64':base64.b64encode(data).decode()}
 return dict(sorted(result.items()))
def diag(phase,file,line,message):return {'phase':phase,'severity':8192,'message':message,'file':'/audit/source/'+PAKE+file+'.class.php','line':line}
def diagnostics(runtime,variant,case):
 ds=[]
 if variant=='original':
  for f,ls in [('pakeGetopt',[53,53,60,84,104,104,109,152,172,192]),('pakeFinder',[526,526,527,528,529,529])]:
   ds += [diag('load',f,n,'Array and string offset access syntax with curly braces is deprecated') for n in ls]
 if runtime=='74':ds.append(diag('generator-load','pakeYaml',54,'Methods with the same name as their class will not be constructors in a future version of PHP; pakeYAMLNode has a deprecated constructor'))
 if variant=='original':ds.append(diag('generator-load','pakeYaml',196,'Array and string offset access syntax with curly braces is deprecated'))
 if runtime=='74' and variant in ['original','exp10']:
  count={'module':3,'admin':2,'crud':3}.get(case,1)
  ds += [diag('generation','pakeApp',357,'Function create_function() is deprecated') for _ in range(count)]
 return ds

def validate(report):
 c.require(c.sha(CONTRACT.read_bytes())==CONTRACT_PIN,'Contract pin mismatch');contract=json.loads(CONTRACT.read_text());manifest=json.loads(c.MANIFEST.read_text())
 c.require(report['status']=='OBSERVED_PENDING_REVIEWED_CONTRACT' and report['phase']=='generate' and report['failures']==[],'Incomplete generation observations')
 c.require('pending' not in report and 'terminal_error' not in report,'Unfinished observation state')
 for k in ['runtime_acceptance','generated_syntax_acceptance','application_acceptance']:c.require(report[k] is False,'Unapproved acceptance flag')
 c.validate_matrix(report['records'],{'generate':CASES});c.require(same(report['identity_before'],report['identity_after']),'Pre/post identity drift')
 identity=report['identity_before'];c.require(same(identity['runtime'],json.loads(c.REFERENCE.read_text())['identity']),'Runtime reference mismatch')
 expectedstage={c.STAGE+'/'+n:c.sha((HERE/n).read_bytes()) for n in ['probe.php','run.sh']}
 for path,pins in manifest['files'].items():
  for variant in ['original','exp10','candidate']:expectedstage[c.STAGE+'/'+variant+'/'+path]=pins[variant]
 c.require(same(identity['stage'],expectedstage),'Stage identity drift')
 program=next(ast.literal_eval(n.value) for n in ast.parse(c.SNAPSHOT.read_text()).body if isinstance(n,ast.Assign) and any(isinstance(t,ast.Name) and t.id=='REMOTE' for t in n.targets))
 c.require(identity['snapshot_helper_sha256']==c.SNAPSHOT_PIN==c.sha(c.SNAPSHOT.read_bytes()) and identity['snapshot_program_sha256']==c.sha(program.encode()),'Snapshot helper/program drift')
 c.require(report['input_pins']=={str(c.MANIFEST):c.sha(c.MANIFEST.read_bytes()),str(c.CASES):c.sha(c.CASES.read_bytes())},'Input pin drift')
 c.require(report['harness_sha256']=={n:c.sha((HERE/n).read_bytes()) for n in c.HARNESS},'Execution harness drift')
 counters={'positive_tasks':0,'expected_removed_function_errors':0,'lint_success':0,'lint_expected_unsubstituted_failure':0,'debug_empty_argument_outputs':0}
 for r in report['records']:
  b=c.parse_record(r,manifest);rt=r['runtime'];v=r['variant'];case=r['case'];control=(rt,v)==('83','exp10')
  c.require(r['command']==f'bash {c.STAGE}/run.sh {rt} {v} generate {case}','Command mismatch')
  outputs=expected_outputs(case,control,contract,manifest);ds=diagnostics(rt,v,case)
  error={'class':'Error','message':'Call to undefined function create_function()','file':'/audit/source/'+PAKE+'pakeApp.class.php','line':357} if control else None
  c.require(type(r['exit']) is int and r['exit']==(10 if control else 0),'Expected task exit mismatch')
  for field,value in [('value',None),('exception',error),('diagnostics',ds),('logs',contract['logs'][rt+'|'+v+'|'+case]),('loaded',{p:pins[v] for p,pins in manifest['files'].items() if '/skeleton/' not in p}),('outputs',outputs if outputs else [])]:c.require(same(b[field],value),'Expected '+field+' mismatch '+str((rt,v,case)))
  stderr=''.join('Deprecated: '+d['message']+' in '+d['file']+' on line '+str(d['line'])+'\n' for d in ds);c.require(r['stderr']==stderr and r['stderr_sha256']==c.sha(stderr.encode()),'Native stderr drift')
  lints=[]
  for path in outputs:
   if path.endswith('.php'):
    for runtime in ['74','83']:
     native=contract['lint_failures'][case+'|'+runtime] if control else {'stdout':'No syntax errors detected in Standard input code\n','stderr':''}
     lints.append({'path':path,'runtime':runtime,'exit':255 if control else 0,**native});counters['lint_expected_unsubstituted_failure' if control else 'lint_success']+=1
  c.require(same(r['lints'],lints),'Exact generated lint matrix mismatch')
  counters['expected_removed_function_errors' if control else 'positive_tasks']+=1
  if not control and (case.endswith('-false') or case.endswith('-zero')):counters['debug_empty_argument_outputs']+=1
 c.require(counters=={'positive_tasks':72,'expected_removed_function_errors':18,'lint_success':168,'lint_expected_unsubstituted_failure':30,'debug_empty_argument_outputs':24},'Outcome inventory mismatch')
 return {'scope':'90 real generation observations only','rows':90,**counters,'debug_false_runtime_arity':'NOT_EXECUTED','generated_application_execution':False,'negative_case_execution':False,'application_acceptance':False}
def main():
 p=argparse.ArgumentParser();p.add_argument('report',type=Path);p.add_argument('output',type=Path);a=p.parse_args();c.require(not a.output.exists(),'Refuse overwrite');summary=validate(json.loads(a.report.read_text()));a.output.write_text(json.dumps({'input_sha256':c.sha(a.report.read_bytes()),'validator_sha256':c.sha(Path(__file__).read_bytes()),'contract_sha256':CONTRACT_PIN,'summary':summary},indent=2)+'\n');print(json.dumps(summary))
if __name__=='__main__':main()
