"""Literal non-vendor notice/component and generated-file declaration mapping.

Source-scope grouping only, not dependency boundary/license inheritance inference.
"""
import argparse,json,re
from pathlib import Path
from build import ROOT,canonical,require,sha,ZIP_PIN
PIN='4cd9212e48d806ce7a5cdf852712f4f685cd32182add9a0ec0dacd46567ed162'
NOTICE=re.compile(r'^(license|copying|copyright)(\.[^/]*)?$',re.I)
GENERATED=re.compile(rb'automatically generated|generated by|do not edit',re.I)
CLIENT_SCOPES={'deployment/uiconf/':'KalturaClient.php','admin_console/web/js/Kaltura/':'KalturaClient.js','plugins/event_notification/providers/bpm/providers/activiti/client/':'ActivitiClient.php'}
DECLARATION=re.compile(rb'\b(?:copyright|license|licensed|version|revision)\b',re.I)
def inspect(path,raw):
 header=raw.split(b'\n')[:100];notice=bool(NOTICE.fullmatch(Path(path).name))
 generated=[i for i,line in enumerate(header,1) if GENERATED.search(line)]
 evidence=[{'line':i,'text':line.decode('utf8','replace')[:240]} for i,line in enumerate(header,1) if DECLARATION.search(line)]
 return notice,generated,evidence

def build(tree,inventory):
 tree=Path(tree);source={r['path']:r for r in inventory['source_members']};require(inventory['source_archive_sha256']==ZIP_PIN,'SOURCE')
 rows=[];notice_scopes={};generated=[]
 for path,row in sorted(source.items()):
  if path.startswith('vendor/'):continue
  p=tree/path;require(not p.is_symlink(),'LINK');raw=p.read_bytes();require(sha(raw)==row['sha256'],'SOURCE_PIN')
  notice,lines,evidence=inspect(path,raw)
  if notice:
   scope=str(Path(path).parent);notice_scopes.setdefault(scope,[]).append({'path':path,'sha256':row['sha256'],'literal_header_declarations':evidence})
  if lines:
   generated.append({'path':path,'sha256':row['sha256'],'declaration_lines':lines,'literal_header_declarations':evidence,'declared_revision':None,'revision_disposition':'UNRESOLVED_UNLESS_LITERAL_EVIDENCE','license_disposition':'FILE_HEADER_EVIDENCE_ONLY_NO_INHERITANCE'})
 for scope,evidence in sorted(notice_scopes.items()):
  prefix='' if scope=='.' else scope+'/'
  members=[(p,r['sha256'],r['bytes']) for p,r in sorted(source.items()) if p.startswith(prefix) and not p.startswith('vendor/')]
  rows.append({'scope_directory':scope,'scope_kind':'DIRECTORY_WITH_LITERAL_NOTICE_NOT_PACKAGE_BOUNDARY','source_files_under_scope':len(members),'source_manifest_sha256':sha(canonical(members)),'notices':evidence,'declared_revision':None,'revision_disposition':'UNRESOLVED_SCOPE_HAS_EXACT_ARCHIVE_REVISION','license_disposition':'NOTICE_PRESENT_APPLICABILITY_NOT_ADJUDICATED'})
 client_scopes=[]
 for prefix,representative in CLIENT_SCOPES.items():
  selected=[r for r in inventory['source_members'] if r['path'].startswith(prefix)]
  require(prefix+representative in source,'CLIENT_SOURCE')
  client_scopes.append({'scope_directory':prefix,'representative_source':prefix+representative,'representative_sha256':source[prefix+representative]['sha256'],'files':[{'path':r['path'],'sha256':r['sha256'],'bytes':r['bytes']} for r in selected],'kind':'SOURCE_CLIENT_DECLARATION_SCOPE_NOT_GENERATION_EXECUTION','archive_revision':ZIP_PIN,'component_revision':None,'license':None,'disposition':'SCOPED_UNRESOLVED_NOT_INHERITED'})
 generator=[r for r in inventory['packaged_php'] if r['path'].startswith('opt/kaltura/clients-generator/')]
 package_clients=[r for r in inventory['packaged_entrypoint_candidates'] if 'generated_client_candidate' in r['class']]
 return {'schema':1,'source_archive_sha256':ZIP_PIN,'inventory_sha256':PIN,'source_client_scopes':client_scopes,'packaged_generator_php_sources':generator,'generator_component_disposition':{'revision':None,'license':None,'status':'EXACT_PUBLISHED_PACKAGE_OWNERS_RECORDED_COMPONENT_METADATA_UNRESOLVED'},'nonvendor_notice_scopes':rows,'original_generated_header_candidates':generated,'packaged_generated_client_candidates':package_clients,'summary':{'source_client_scopes':len(client_scopes),'packaged_generator_php_sources':len(generator),'nonvendor_notice_scopes':len(rows),'original_generated_header_candidates':len(generated),'packaged_generated_client_candidates':len(package_clients)},'limitations':['Generated markers may be examples or generated non-client models; not all clients identify themselves','Directory notice scopes overlap and imply no blanket license','Package generator output revision/license remain explicit unresolved per existing package identities; runtime generation not required by this census'],'task_1_1_complete':False}
def main():
 p=argparse.ArgumentParser();p.add_argument('--tree',required=True);p.add_argument('--output',required=True);a=p.parse_args()
 raw=(ROOT/'doc/php83/evidence/inventory-closure-r1/inventory-reviewed.json').read_bytes();require(sha(raw)==PIN,'INPUT_PIN')
 with Path(a.output).open('xb') as f:f.write(canonical(build(a.tree,json.loads(raw))))
if __name__=='__main__':main()
