"""Offline literal attribution evidence; never imports or executes bundled PHP."""
import argparse,hashlib,json,pathlib,re,zipfile
P=argparse.ArgumentParser();P.add_argument('--output',required=True);a=P.parse_args();out=pathlib.Path(a.output)
if out.exists():raise SystemExit('refuse existing output')
archive=pathlib.Path('/tmp/kaltura-php83-audit/Rigel-18.20.0.zip'); H=lambda b:hashlib.sha256(b).hexdigest();pin='58d534d09b3b75c9a8333957268c884f79032638b2d44a278b1992fda1b0ab28'
assert H(archive.read_bytes())==pin
z=zipfile.ZipFile(archive);root='server-Rigel-18.20.0/'; files={n[len(root):]:z.read(n) for n in z.namelist() if n.startswith(root+'vendor/') and not n.endswith('/')}
ledgerpath=pathlib.Path('doc/php83/evidence/inventory-ledger/ledger.json');ledger=json.loads(ledgerpath.read_text()); sources={}
def ref(p,ranges):
 b=files[p];lines=b.decode('utf8','replace').splitlines();sources[p]={'sha256':H(b),'bytes':len(b),'line_count':len(lines),'excerpts':[{'start':lo,'end':min(hi,len(lines)),'text':'\n'.join(lines[lo-1:hi])} for lo,hi in ranges]};return p
rows=[]
def row(d,version,license,scope,refs,remaining):
 rows.append({'directory':'vendor/'+d+'/','declared_version':version,'declared_license':license,'scope':scope,'evidence':[ref(p,rs) for p,rs in refs],'remaining':remaining,'whole_directory_attribution_complete':False})
row('IP2Location',None,'Database README: GENERAL PUBLIC LICENSE, June 1991','Database notice only; generator Software Version 4.0.0 is NOT a library version', [('vendor/IP2Location/ip_files/readme.txt',[(1,35)])],['Library version/license unresolved; database timestamp and generator version do not prove library or data snapshot consistency.'])
row('MaxMind','GeoIP2 v2.4.5',None,'GeoIP2 Client version declaration, NOT MaxMind Db reader version',[('vendor/MaxMind/GeoIP2/WebService/Client.php',[(43,53)])],['GeoIP2/Db reader exact revisions and license attribution unresolved.'])
row('PHPMailer','5.2.1','LGPL declaration; bundled license text version 2.1','Top-level PHPMailer only, not nested Symfony copy',[('vendor/PHPMailer/class.phpmailer.php',[(1,35),(324,328)]),('vendor/PHPMailer/LICENSE',[(1,11)])],['Exact upstream revision and modified-file comparison unverified; no or-later grant inferred from generic license appendix.'])
row('ZendFramework','1.9.6','New BSD declaration; bundled three-condition redistribution text','Zend Version declaration and matching bundled Zend notice',[('vendor/ZendFramework/library/Zend/Version.php',[(1,36)]),('vendor/ZendFramework/LICENSE.txt',[(1,32)])],['Transitive exceptions and exact upstream revision unverified.'])
row('akamai',None,None,'Per-file revision notice only',[('vendor/akamai/token/RijndaelAlgorithm.php',[(1,17)])],['File revision 5428 is not an Akamai package version; mixed notices and license rights unresolved.'])
row('avro',None,'See separate Composer metadata records and exact bundled license texts','Mixed bundle, not one version/license',[('vendor/avro/composer/installed.json',[(1,18)]),('vendor/avro/flix-tech/confluent-schema-registry-api/LICENSE',[(1,14)]),('vendor/avro/wikimedia/avro/LICENSE.txt',[(1,5),(205,209),(228,232),(252,256),(283,287)]),('vendor/avro/composer/LICENSE',[(1,18)])],['15 manifest declarations are not 15 installed byte identities; 13 expected name-prefixes absent. Exact upstream revision-to-byte verification and bundled subcomponent rights remain open.'])
row('aws','2.7.21','Apache License 2.0 bundled root text','AWS SDK declaration only, not all bundled dependencies',[('vendor/aws/Aws/Common/Aws.php',[(1,33)]),('vendor/aws/LICENSE.md',[(1,4)]),('vendor/aws/Guzzle/Common/Version.php',[(1,13)]),('vendor/aws/Doctrine/Common/Cache/Version.php',[(1,25)]),('vendor/aws/Symfony/Component/EventDispatcher/LICENSE',[(1,20)])],['Guzzle 3.9.2 and Doctrine cache 1.4.0-DEV are separate declarations; Monolog, Symfony, Doctrine, Guzzle transitive license/revision completion remains open.'])
row('facebook-sdk-php-v5-customized','5.0.0','Facebook-specific permission limited to Facebook web services/APIs; retained notice','Facebook.php exact header, NOT a generic MIT attribution',[('vendor/facebook-sdk-php-v5-customized/Facebook.php',[(1,23),(54,66)])],['Customized source-to-upstream delta/revision and per-file rights unverified; Graph API v7.0 is not SDK version.'])
row('fpdf','1.7','Bundled permissive use/copy/modify/distribute/sublicense/sell permission text; no SPDX inferred','FPDF core and exact local license text',[('vendor/fpdf/fpdf.php',[(1,12)]),('vendor/fpdf/license.txt',[(1,6)])],['Font/makefont component attribution and upstream revision unverified.'])
row('google-api-php-client',None,'Apache License 2.0 explicit source header','Legacy Google Client, no version established',[('vendor/google-api-php-client/src/Google_Client.php',[(1,16)]),('vendor/google-api-php-client/LICENSE',[(1,6)])],['No version inferred from naming; exact revision and generated service provenance unresolved.'])
row('google-api-php-client-1.1.2','1.1.5','Apache License 2.0 explicit source header','Google Client LIBVER conflicts with directory suffix 1.1.2',[('vendor/google-api-php-client-1.1.2/src/Google/Client.php',[(1,30)]),('vendor/google-api-php-client-1.1.2/LICENSE',[(1,6)])],['Mixed/customized-tree possibility not adjudicated; exact upstream revision and service provenance unresolved.'])
row('htmlpurifier','4.6.0','LGPL version 2.1 or later explicitly granted in source header','HTMLPurifier declaration and license',[('vendor/htmlpurifier/library/HTMLPurifier.php',[(21,38),(56,67)]),('vendor/htmlpurifier/LICENSE',[(1,11)])],['Exact upstream revision and transitive exceptions unverified.'])
row('mantis',None,None,'Single bundled mantisClient file, not assumed complete Mantis release',[('vendor/mantis/mantisClient.class.php',[(1,12)])],['No package version/license established.'])
row('nusoap','0.9.5','LGPL version 2.1 or later explicit header','NuSOAP base declaration and per-file CVS revision',[('vendor/nusoap/class.nusoap_base.php',[(1,23),(94,112)])],['CVS revision 1.56 belongs to this file, not a full release commit; per-file upstream mapping remains open.'])
row('phpGangsta',None,'BSD License label/link; clause variant not established','Edited GoogleAuthenticator source header',[('vendor/phpGangsta/GoogleAuthenticator.php',[(1,12)])],['Exact version/revision, complete license text and variant unresolved; edited header retained.'])
row('propel','1.4.2','LGPL label without version in inspected header','Top-level Propel only',[('vendor/propel/Propel.php',[(1,21),(88,96)])],['File SVN revision 1691 not package revision; exact LGPL version and nested runtime/generator relationships unresolved.'])
row('symfony','1.0.1',None,'Bundled VERSION; sfCore references a missing top-level LICENSE',[('vendor/symfony/VERSION',[(1,1)]),('vendor/symfony/util/sfCore.class.php',[(1,17)]),('vendor/symfony/vendor/phpmailer/class.phpmailer.php',[(1,27),(123,130)]),('vendor/symfony/vendor/pake/pakeApp.class.php',[(1,27)]),('vendor/symfony/vendor/propel-generator/LICENSE',[(1,8)])],['Nested Propel license not automatically Symfony license; nested PHPMailer 1.73, pake 1.1.DEV distinct from top-level versions; other nested components unresolved.'])
row('symfony-data',None,None,'Header says part of Symfony, does not declare matching whole-tree release',[('vendor/symfony-data/bin/symfony.php',[(1,9)])],['Do not inherit version 1.0.1 or nested license merely from adjacent directory; source lineage and license unresolved.'])
row('tfpdf','1.25','LGPL label without version in tFPDF header','tFPDF header/date 2018-03-19; fonts have separate notices',[('vendor/tfpdf/tfpdf.php',[(1,12)]),('vendor/tfpdf/font/unifont/LICENSE_OFL.txt',[(1,12)]),('vendor/tfpdf/font/unifont/DejaVu_LICENSE.txt',[(1,18)])],['Exact LGPL version and complete per-font attribution remain open.'])
row('webex',None,None,'Read-only filename inventory and representative header only',[('vendor/webex/xml/WebexXmlClient.class.php',[(1,14)])],['No SDK version/license proven; service/API versions cannot substitute release identity.'])
assert {r['directory'] for r in rows}=={r['directory'] for r in ledger['dependencies']}
packages=[]
for p in json.loads(files['vendor/avro/composer/installed.json'])['packages']:
 prefix='vendor/avro/'+p['name']+'/'
 packages.append({'name':p['name'],'version':p['version'],'license':p.get('license'),'source':p.get('source'),'install_path':p.get('install-path'),'metadata_pointer':'/packages/'+str(len(packages)),'files_at_expected_name_prefix':sum(n.startswith(prefix) for n in files),'source_revision_bytes_verified':False})
for r in rows:
 subset=[{'path':p,'sha256':H(b),'bytes':len(b)} for p,b in sorted(files.items()) if p.startswith(r['directory'])]
 r['archive_file_count']=len(subset);r['file_identity_manifest_sha256']=H(json.dumps(subset,sort_keys=True,separators=(',',':')).encode())
report={'schema':1,'scope':'Literal bundled metadata/header attribution, not runtime, legal compliance, whole SBOM or dependency upgrade advice. No application execution.','archive':{'path':str(archive),'sha256':pin},'prior_ledger':{'path':str(ledgerpath),'sha256':H(ledgerpath.read_bytes())},'rows':rows,'sources':sources,'composer_metadata':packages,'summary':{'directories':len(rows),'version_declarations':sum(r['declared_version'] is not None for r in rows),'license_evidence_rows':sum(r['declared_license'] is not None for r in rows),'whole_directory_attributions_complete':0,'composer_declared_packages':len(packages),'composer_name_prefix_present':sum(p['files_at_expected_name_prefix']>0 for p in packages),'vendor_files':len(files)},'method':'ZIP reads only. Literal metadata inventory is not structural code discovery; no graph-based conclusion. No external attribution relied on. SHA256 identities do not authenticate upstream revisions.'}
assert H(archive.read_bytes())==pin
out.write_text(json.dumps(report,indent=2,ensure_ascii=False)+'\n');print(json.dumps(report['summary']))
