#!/bin/sh
set -e
# Automatically added by dh_installinit/13.14.1ubuntu5
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/kaltura-batch" ] ; then
	invoke-rc.d kaltura-batch stop || exit 1
fi
# End automatically added section
