#!/bin/sh
set -e
# Automatically added by dh_installinit/13.14.1ubuntu5
if [ "$1" = "remove" ] && [ -x "/etc/init.d/kaltura-populate" ] ; then
	chmod -x "/etc/init.d/kaltura-populate" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d kaltura-populate remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installinit/13.14.1ubuntu5
if [ "$1" = "remove" ] && [ -x "/etc/init.d/kaltura-sphinx" ] ; then
	chmod -x "/etc/init.d/kaltura-sphinx" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d kaltura-sphinx remove >/dev/null
fi
# End automatically added section
