#!/bin/sh
set -e
# Automatically added by dh_installinit/13.14.1ubuntu5
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/kaltura-sphinx" ] ; then
	chmod +x "/etc/init.d/kaltura-sphinx" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.14.1ubuntu5
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/kaltura-populate" ] ; then
	chmod +x "/etc/init.d/kaltura-populate" >/dev/null || true
fi
# End automatically added section
